include:
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: urchin_left nice_view_adapter nice_view_custom
  - board: nice_nano
    shield: urchin_right nice_view_adapter nice_view_custom 
